repos:
  - repo: local
    hooks:
      - id: check-architecture
        name: Check Architecture Compliance
        entry: python scripts/validation/check_architecture.py
        language: system
        pass_filenames: false
        always_run: true
        
      - id: check-system-state
        name: Update System State
        entry: python scripts/validation/update_system_state.py
        language: system
        pass_filenames: false
        always_run: true
        
      - id: check-no-hardcoding
        name: Check for Hardcoded Values
        entry: python scripts/validation/check_hardcoding.py
        language: system
        types: [python]
        
      - id: check-error-handling
        name: Verify Error Handling
        entry: python scripts/validation/check_error_handling.py
        language: system
        types: [python]
        
      - id: check-complexity
        name: Check Code Complexity
        entry: python scripts/validation/check_complexity.py
        language: system
        types: [python]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=100', '--max-complexity=10']

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ['--profile', 'black']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]